/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/cat_thing_copy.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/model/cat_thing_copy.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="FAB_converted">
        <group name="FAB_converted_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="cat_thing_copyfbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Armature"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}>
                  <group name="Object_5">
                    <group name="Root_01" rotation={[Math.PI / 2, 0, 0]}>
                      <primitive object={nodes.Spine_02} />
                      <group
                        name="Look_Control_057"
                        position={[0.776, 0.984, 6.084]}
                      />
                    </group>
                    <group
                      name="Object_64"
                      position={[0, 50.682, -16.503]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_66"
                      position={[0, 50.682, -16.503]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_68"
                      position={[0, 50.682, -16.503]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_70"
                      position={[0, 50.682, -16.503]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_72"
                      position={[5.841, 77.454, -9.531]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_74"
                      position={[0, 71.566, 0.139]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}>
                      <skinnedMesh
                        name="Object_75"
                        geometry={nodes.Object_75.geometry}
                        material={materials.EyesV2}
                        skeleton={nodes.Object_75.skeleton}
                        morphTargetDictionary={
                          nodes.Object_75.morphTargetDictionary
                        }
                        morphTargetInfluences={
                          nodes.Object_75.morphTargetInfluences
                        }
                      />
                      <skinnedMesh
                        name="Object_76"
                        geometry={nodes.Object_76.geometry}
                        material={materials.Body}
                        skeleton={nodes.Object_76.skeleton}
                        morphTargetDictionary={
                          nodes.Object_76.morphTargetDictionary
                        }
                        morphTargetInfluences={
                          nodes.Object_76.morphTargetInfluences
                        }
                      />
                      <skinnedMesh
                        name="Object_77"
                        geometry={nodes.Object_77.geometry}
                        material={materials.Mouth}
                        skeleton={nodes.Object_77.skeleton}
                        morphTargetDictionary={
                          nodes.Object_77.morphTargetDictionary
                        }
                        morphTargetInfluences={
                          nodes.Object_77.morphTargetInfluences
                        }
                      />
                    </group>
                    <group
                      name="Object_78"
                      position={[0, 60.117, 5.492]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_80"
                      position={[0, 60.117, 5.492]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_82"
                      position={[-0.232, 69.651, 19.524]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_84"
                      position={[11.373, 51.687, 10.024]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
                <group
                  name="Backpack"
                  position={[0, 50.682, -16.503]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Backpack001"
                  position={[0, 50.682, -16.503]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Backpack002"
                  position={[0, 50.682, -16.503]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Backpack004"
                  position={[0, 50.682, -16.503]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Button001"
                  position={[5.841, 77.454, -9.531]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Cat"
                  position={[0, 71.566, 0.139]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Collar"
                  position={[0, 60.117, 5.492]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Collar_Metal"
                  position={[0, 60.117, 5.492]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Glasses"
                  position={[-0.232, 69.651, 19.524]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Handle"
                  position={[11.373, 51.687, 10.024]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
          <skinnedMesh
            name="Object_65"
            geometry={nodes.Object_65.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_65.skeleton}
          />
          <skinnedMesh
            name="Object_67"
            geometry={nodes.Object_67.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_67.skeleton}
          />
          <skinnedMesh
            name="Object_69"
            geometry={nodes.Object_69.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_69.skeleton}
          />
          <skinnedMesh
            name="Object_71"
            geometry={nodes.Object_71.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_71.skeleton}
          />
          <skinnedMesh
            name="Object_73"
            geometry={nodes.Object_73.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_73.skeleton}
          />
          <skinnedMesh
            name="Object_79"
            geometry={nodes.Object_79.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_79.skeleton}
          />
          <skinnedMesh
            name="Object_81"
            geometry={nodes.Object_81.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_81.skeleton}
          />
          <skinnedMesh
            name="Object_83"
            geometry={nodes.Object_83.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_83.skeleton}
          />
          <skinnedMesh
            name="Object_85"
            geometry={nodes.Object_85.geometry}
            material={materials.Accessories}
            skeleton={nodes.Object_85.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/cat_thing_copy.glb");
