/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/catoon_coffe.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/model/catoon_coffe.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.173, 0.717, -0.057]}
        rotation={[0.017, 0.055, -0.209]}>
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}>
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}>
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}>
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}>
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}>
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.285, 1.063, 0.005]}
        rotation={[0.016, 0.081, -0.3]}
        scale={[0.731, 0.54, 0.731]}>
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[1.656, 1.029, 0.298]}
        rotation={[0.737, -0.558, 0.351]}
        scale={[0.322, 0.307, 0.352]}>
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}>
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[1.313, 0.451, 0.651]}
        rotation={[0.691, -0.918, 0.477]}
        scale={[0.137, 0.166, 0.157]}>
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[1.566, 0.667, 0.385]}
        rotation={[0.184, -0.053, 0.265]}
        scale={[0.104, 0.127, 0.12]}>
        <mesh
          geometry={nodes.Object_43.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Object_44.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <group
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[0.957, 1.011, 1.028]}>
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.OH_Outline_Material}
        />
      </group>
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials["Material.002"]}
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}
      />
      <mesh
        geometry={nodes.Object_27.geometry}
        material={materials["Material.002"]}
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}
      />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials["Material.002"]}
        position={[0.012, 0.054, -0.009]}
        rotation={[0.017, 0.055, -0.209]}
        scale={[1, 1.056, 1.074]}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials.OH_Outline_Material}
        position={[1.332, 0.002, 0.855]}
        rotation={[0.013, 0.441, 0.037]}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.OH_Outline_Material}
        position={[0.783, -0.094, 0.827]}
        rotation={[0.611, -0.365, -0.537]}
        scale={[0.55, 0.982, 0.869]}
      />
      <mesh
        geometry={nodes.Object_53.geometry}
        material={materials.OH_Outline_Material}
        position={[-1.557, 1.575, 0.287]}
        rotation={[-1.721, 0.003, 0.19]}
        scale={[-0.043, 0.043, 0.043]}
      />
      <mesh
        geometry={nodes.Object_55.geometry}
        material={materials.OH_Outline_Material}
        position={[2.093, 0.793, 1.094]}
        rotation={[-1.721, 0.003, 0.19]}
        scale={[-0.031, 0.031, 0.031]}
      />
      <mesh
        geometry={nodes.Object_57.geometry}
        material={materials.OH_Outline_Material}
        position={[1.338, -0.573, -0.797]}
        rotation={[-1.721, 0.003, 0.19]}
        scale={[-0.067, 0.067, 0.067]}
      />
      <mesh
        geometry={nodes.Object_59.geometry}
        material={materials.OH_Outline_Material}
        position={[-1.01, 2.102, 0.928]}
        rotation={[-1.588, 0.09, 0.625]}
        scale={[-0.036, 0.036, 0.036]}
      />
      <mesh
        geometry={nodes.Object_61.geometry}
        material={materials.OH_Outline_Material}
        position={[2.12, 0.411, 0.107]}
        rotation={[-1.59, 0.414, 0.631]}
        scale={[-0.063, 0.063, 0.063]}
      />
      <mesh
        geometry={nodes.Object_63.geometry}
        material={materials.OH_Outline_Material}
        position={[-1.593, -0.374, 0.862]}
        rotation={[-1.467, 0.109, 0.092]}
        scale={[-0.086, 0.086, 0.086]}
      />
      <mesh
        geometry={nodes.Object_65.geometry}
        material={materials.OH_Outline_Material}
        position={[0.772, 2.625, 0.578]}
        rotation={[-1.974, -0.203, 0.873]}
        scale={[-0.063, 0.063, 0.063]}
      />
      <mesh
        geometry={nodes.Object_67.geometry}
        material={materials.OH_Outline_Material}
        position={[0.836, -0.75, 1.584]}
        rotation={[-2.339, 0.412, 0.208]}
        scale={[-0.042, 0.042, 0.042]}
      />
      <mesh
        geometry={nodes.Object_69.geometry}
        material={materials.OH_Outline_Material}
        position={[-1.206, 0.826, 2.382]}
        rotation={[-1.628, -0.366, 1.425]}
        scale={[-0.039, 0.039, 0.039]}
      />
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials.OH_Outline_Material}
        position={[-1.527, 2.773, -2.239]}
        rotation={[-1.721, 0.003, 0.19]}
        scale={[-0.043, 0.043, 0.043]}
      />
      <mesh
        geometry={nodes.Object_73.geometry}
        material={materials.OH_Outline_Material}
        position={[1.637, 0.905, -1.099]}
        rotation={[-2.487, -0.579, 0.157]}
        scale={[-0.063, 0.063, 0.063]}
      />
      <mesh
        geometry={nodes.Object_75.geometry}
        material={materials.OH_Outline_Material}
        position={[2.036, -0.04, 1.296]}
        rotation={[-2.339, 0.412, 0.208]}
        scale={[-0.026, 0.026, 0.026]}
      />
      <mesh
        geometry={nodes.Object_77.geometry}
        material={materials.OH_Outline_Material}
        position={[-0.947, 2.405, -1.291]}
        rotation={[-1.588, 0.09, 0.625]}
        scale={[-0.037, 0.037, 0.037]}
      />
      <mesh
        geometry={nodes.Object_79.geometry}
        material={materials.OH_Outline_Material}
        position={[1.3, 2.316, -1.363]}
        rotation={[-1.974, -0.203, 0.873]}
        scale={[-0.036, 0.036, 0.036]}
      />
    </group>
  );
}

useGLTF.preload("/catoon_coffe.glb");
