/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/cute_enemy_slime.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/model/cute_enemy_slime.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.BigSlime_BigSlime1_0.geometry}
          material={materials.BigSlime1}
          position={[0, -2.047, 0.088]}
        />
        <mesh
          geometry={nodes.SmallSlime_SmallSlime1_0.geometry}
          material={materials.SmallSlime1}
          position={[0, -1.636, 0.079]}
          scale={0.903}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cute_enemy_slime.glb");
