/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/little_mrastronaut.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/model/little_mrastronaut.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes["Box034_08_-_Default_0"].geometry}
            material={materials["08_-_Default"]}
          />
          <mesh
            geometry={nodes["Box034_08_-_Default_0_1"].geometry}
            material={materials["08_-_Default"]}
          />
          <mesh
            geometry={nodes["Box034_08_-_Default_0_2"].geometry}
            material={materials["08_-_Default"]}
          />
        </group>
        <mesh
          geometry={nodes["Box032_14_-_Default_0"].geometry}
          material={materials["14_-_Default"]}
          position={[0, 69.644, -0.731]}
          rotation={[-1.396, 0, 0]}
        />
        <mesh
          geometry={nodes["tyFlow007Low002_04_-_Default_0"].geometry}
          material={materials["04_-_Default"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Object005_04_-_Defaulth_0"].geometry}
          material={materials["04_-_Defaulth"]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes["Box033_02_-_Default_0"].geometry}
          material={materials["02_-_Default"]}
          position={[0, 69.644, -0.731]}
          rotation={[-1.396, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/little_mrastronaut.glb");
