// Одноразовый сид существующих 5 проектов в коллекцию `projects` (ru + en).
// Запуск: node node_modules/.pnpm/tsx@*/node_modules/tsx/dist/cli.mjs scripts/seed-projects.ts
// Идемпотентно: проект с уже существующим slug пропускается.

import { getPayload } from "payload";
import config from "@payload-config";

type Loc = {
  title: string;
  shortDesc: string;
  fullDesc: string;
  features: string[];
};

type Seed = {
  slug: string;
  order: number;
  techStack: string[];
  legacyFolder: string;
  legacyImageCount: number;
  ru: Loc;
  en: Loc;
};

const PROJECTS: Seed[] = [
  {
    slug: "t-catalog-admin",
    order: 0,
    legacyFolder: "t-catalog-admin",
    legacyImageCount: 32,
    techStack: ["Next.js", "TypeScript", "Tailwind", "NestJS", "PostgreSQL", "BullMQ", "Redis", "Coolify", "SMTP", "Robokassa", "YooKassa"],
    ru: {
      title: "Т-Каталог - Админка WEB + Бот",
      shortDesc: "Управляющая ERP/CRM экосистема с визуальным программированием бизнес-логики магазинов.",
      fullDesc: "Административная консоль b2b-маркетплейса. Внедрен визуальный конструктор логических цепочек (Event-driven сценарии модальных окон чекаута, правила обмена тары, условные триггеры). Интегрирована матрица SKU-модификаторов для адаптивных сеток одежды (размер, рост, цвет с автономными остатками и ценами), пайплайн юридического онбординга (KYC проверка ИНН/ОГРН), гибкий менеджер жизненного цикла кастомных статусов и SMTP-маршрутизатор уведомлений.",
      features: [
        "Визуальный билдер логических последовательностей и условных сценариев для окон оформления заказа",
        "Гибкие матрицы SKU-вариаций (размерные сетки, рост, цвет с независимым складским учетом)",
        "Универсальный движок промокодов с многоуровневыми лимитами использования и порогами активации",
      ],
    },
    en: {
      title: "T-Catalog - Management Dashboard",
      shortDesc: "Multi-tenant ERP/CRM platform with visual business logic programming engines.",
      fullDesc: "An administrative console for marketplace orchestrators. Built a visual workflow node builder (event-driven checkout modal sequences, conditional logic triggers, custom package exchange rules). Integrated advanced SKU modification matrices for apparel (size grids, height, color variants with independent stock tracking), legal onboarding workflows (KYC entity validation via tax numbers), custom status managers, and automated SMTP routing.",
      features: [
        "Visual workflow builder managing sequential conditional logic and custom checkout checkout steps",
        "Multi-attribute SKU variation matrices handling size grids, height, and independent inventory limits",
        "Granular promotional coupon engine supporting multi-level usage caps and specific order thresholds",
      ],
    },
  },
  {
    slug: "t-catalog-client",
    order: 1,
    legacyFolder: "t-catalog-client",
    legacyImageCount: 12,
    techStack: ["Next.js", "TypeScript", "Tailwind", "Redux Toolkit", "Supabase", "Coolify", "ZOD", "Grammy"],
    ru: {
      title: "Т-Каталог - Бот + Магазин",
      shortDesc: "Высокопроизводительная мультибрендовая витрина в формате Telegram Mini App.",
      fullDesc: "Клиентское SSR/SPA приложение, адаптированное под встроенный рантайм Telegram. Динамически интерпретирует скомпилированные сервером скрипты визуального билдера (интерактивные проверки бутылей, кастомные подсказки). Поддерживает мгновенную фильтрацию многофакторных SKU-вариаций товаров, расчет промокодов на уровне БД и бесшовную синхронизацию с нативными элементами навигации мессенджера.",
      features: [
        "Динамический рендеринг условных диалогов чекаута, запрограммированных в панели управления",
        "Клиентская фильтрация сложных товарных модификаций со связкой ценовых снапшотов в СУБД",
        "Адаптивный роутинг с интеграцией нативных интерфейсов Telegram (BackButton, openLink)",
      ],
    },
    en: {
      title: "T-Catalog - Storefront Application",
      shortDesc: "High-performance E-commerce client running as a Telegram Mini App.",
      fullDesc: "A storefront application fully optimized for embedded runtime constraints. Dynamically parses and renders structural JSON node sequences generated by the admin's visual logic builder (handling custom container deposit logic and dynamic checklist prompts). Supports instant processing of complex product variations, database-level coupon validation, and native Telegram UI elements.",
      features: [
        "Dynamic client-side parsing of conditional checkout workflows configured via the visual node builder",
        "Integration of multi-attribute variation filters matched with database-level pricing snapshots",
        "Context-aware routing seamlessly mapped to native Telegram UI (BackButton, openLink)",
      ],
    },
  },
  {
    slug: "rulme-admin",
    order: 2,
    legacyFolder: "rulme-admin",
    legacyImageCount: 8,
    techStack: ["Next.js", "TypeScript", "Node.js", "Supabase", "Tailwind", "Coolify"],
    ru: {
      title: "Рули Сюда - Админка",
      shortDesc: "Диспетчерский бэк-офис агрегатора автосервисных услуг.",
      fullDesc: "Специализированный пульт координации заявок и мониторинга активности. Настроена real-time диспетчеризация входящего потока данных и выделенная вкладка перехвата незавершенных форм. Панель агрегирует лог транзакций, профили мастеров и позволяет операторам бесшовно контролировать финансовые цепочки.",
      features: [
        "Интерфейс перехвата брошенных форм для удержания ушедших на втором шаге клиентов",
        "Централизованный шлюз маршрутизации payload-данных в multi-bot инфраструктуре",
        "Аналитический дашборд для сегментации пользователей и контроля логов авторизации",
      ],
    },
    en: {
      title: "Rulme - Operator Console",
      shortDesc: "Administrative command center for dispatching automotive service marketplace requests.",
      fullDesc: "A real-time dispatch dashboard monitoring active pipelines and managing service listings. Designed with a dedicated capture view for partial or unsubmitted application forms. Aggregates live transaction logs, master registration records, and allows operators to audit financial flows without delay.",
      features: [
        "Incomplete form intercept layout designed to recover drop-off leads at early funnel stages",
        "Centralized messaging engine dispatching telemetry payloads across a multi-bot system",
        "Analytical tracking layer for user segment classification and telemetry access logs",
      ],
    },
  },
  {
    slug: "rulme-client",
    order: 3,
    legacyFolder: "rulme-client",
    legacyImageCount: 19,
    techStack: ["Next.js", "TypeScript", "REST", "TW", "PM2", "Grammy", "Coolify"],
    ru: {
      title: "Рули Сюда - Бот + Сервис для автовладельцев",
      shortDesc: "Telegram Mini App агрегатор автосервисов с умным трекингом воронки.",
      fullDesc: "Интерактивный клиентский сервис для подбора автомастеров. Внедрена двухэтапная форма заявки со скрытым фоновым сохранением: система фиксирует контакты на первом шаге и изолирует 'брошенные' на этапе спецификации машины формы. Интегрировано отслеживание состояния активных корзин с автоматической фиксацией нереализованных суточных заявок.",
      features: [
        "Двухэтапная отправка с фоновым кэшированием стейта для захвата частичных лидов",
        "Автоматическая классификация неактивных сессий и контроль возраста брошенных корзин",
        "Кастомный Media Viewer для вложений в заявках с динамической ACL-валидацией прав",
      ],
    },
    en: {
      title: "Rulme - Customer Interface",
      shortDesc: "Telegram Mini App automotive marketplace with integrated conversion tracking loops.",
      fullDesc: "An interactive vehicle repair matching app. Implemented a multi-step checkout with implicit background payload tracking: the system captures user contacts at stage one and logs details if the vehicle specification stage is abandoned. Monitors active carts to catch and display unsubmitted 24-hour-old requests.",
      features: [
        "Multi-stage checkout with silent background state caching to capture partial leads",
        "Automatic session classification indexing idle users and aging incomplete carts",
        "Custom-built Media Viewer for order attachments with real-time API-level ACL validation",
      ],
    },
  },
  {
    slug: "bitovki36",
    order: 4,
    legacyFolder: "bitovki36",
    legacyImageCount: 7,
    techStack: ["Next.js", "TypeScript", "Supabase", "TW", "Docker", "PM2", "Grammy"],
    ru: {
      title: "Бытовки 36 - CRM + Бот",
      shortDesc: "Корпоративная логистическая платформа для промышленного сектора.",
      fullDesc: "Внутренняя распределенная CRM-система для автоматизации цепочек поставок, складского учета и генерации отчетности. Реализована глубокая интеграция с amoCRM на базе реверс-инжиниринга API. Локальная сетевая инфраструктура развернута в закрытом контуре с шифрованием и автоматической ротацией SSL-сертификатов.",
      features: [
        "Двусторонняя синхронизация сущностей и обработка вебхуков amoCRM без документации",
        "Автоматический перезапуск рантайма (< 1 мин) с сохранением стейта процессов через PM2",
        "Standalone выпуск SSL-сертификатов Certbot в закрытых портах через DNS валидацию",
      ],
    },
    en: {
      title: "Bitovki 36 - Corporate CRM",
      shortDesc: "Enterprise logistics management framework for industrial supply chains.",
      fullDesc: "Internal operational platform handling storage audits, automated contract logic, and inventory flows. Built a complete amoCRM data integration layer entirely via API reverse-engineering. Deployed the application into an isolated local network loop featuring automated SSL rotation routines.",
      features: [
        "Two-way asset synchronization and webhook ingestion mapping undocumented amoCRM endpoints",
        "System-level process persistence recovering software runtime state under 1 minute via PM2",
        "Standalone Certbot SSL configuration over restricted port channels using DNS challenges",
      ],
    },
  },
];

const payload = await getPayload({ config });

for (const p of PROJECTS) {
  const existing = await payload.find({
    collection: "projects",
    where: { slug: { equals: p.slug } },
    limit: 1,
    overrideAccess: true,
  });
  if (existing.docs.length > 0) {
    console.log(`skip (exists): ${p.slug}`);
    continue;
  }

  const created = await payload.create({
    collection: "projects",
    locale: "ru",
    overrideAccess: true,
    data: {
      slug: p.slug,
      order: p.order,
      techStack: p.techStack,
      githubUrl: "",
      legacyFolder: p.legacyFolder,
      legacyImageCount: p.legacyImageCount,
      title: p.ru.title,
      shortDesc: p.ru.shortDesc,
      fullDesc: p.ru.fullDesc,
      features: p.ru.features.map((text) => ({ text })),
    },
  });

  await payload.update({
    collection: "projects",
    id: created.id,
    locale: "en",
    overrideAccess: true,
    data: {
      title: p.en.title,
      shortDesc: p.en.shortDesc,
      fullDesc: p.en.fullDesc,
      features: p.en.features.map((text) => ({ text })),
    },
  });

  console.log(`seeded: ${p.slug} (id ${created.id})`);
}

console.log("seed done");
process.exit(0);
